{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysql-credentials",
    "namespace": "training",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysql-credentials",
        "namespace": "training",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "connection": "AgBer76Tc+4AzvFxSgDLTdpsaGC54shBnInLt8W1xpUIdVOQs4VItZ+ZJqB5adG9PNf6La4s/6gpZaWeWdU+c5TbJ1abZEiZi0bkjVZRVla0+LdVrBg2ouAtYCxquUQOXR1pESMC668BgcP3BRe6z5HPdiFoYw0A4AFo1fR1Ta74huVvTkWWgde9thfPKZ9DR8KFeiqmxbGAGO3DVXP9lLq2y74b0dyoE3SkSsidcwPVAbEJcDrJTy35GfDLVaMqzOGh83Y/u9CBrFlRDQqUFIZ4yR3m2AKy6/ohRjhp+6dHaMfaWxK0tiuucYKcm2fZ179KfFMmNYhE0JxXLEg137Y/OBPIjN+4mq/9qpp46SuVZ5gn0fIXDk6kIca461uDPj7VM1T/TU/Z8dnctSh8JYpp2lucs5AliU7vTHbKtoS+P6YS2rGwCNk2dLelHVn0dRy2y31dTutGFQV0duSfL8rGht9AS2ZpY86dmCcN2tZWNQnaOPXGpEO9F1vRGfnXuOr+8rYujGWbtFcmW6UrxTCxZT6fgC0bQhqA0AceGVt2IGB49hYlOa9WkqtxQfOM/vEDYg/OeYCvCRavecC/HnqKEcgSNtqkUCjKuwrgfwyws1LBCFGYh3lCLcvUm5ayjRDp2Z4Y+VI11VF8Usx1o/KxxY7jlx6LvdFUukEK0tXNlIh+n1azxm/wYdw88Gg5DqAcfDFgXm2Hgr4uDmIIJh9WKmSf+9/euaQDHKAD+jsxlEY=",
      "password": "AgC3oXVhT2pkmJXI85fCSb7N1YNGmt1zS5wnbVppzhMOkktIsvEWqafHUf5LpG1/xI29RWTIwQWIPKCxpVD2/JO85oHHHStM0pE9O4OG9oQ9rZzM0M7ISCA8senkCh4pyB2R0Eg+ylAIlorXpmcOV5+wAac0s0c0SEbZh3VUVNg4Exhc/8CXFWoLCB1akcRkUNEoL96AaNhpDMklHxXAlqc1/Lg/BO34up9awVe6LIIuy9a/p1xuqOhD3+POqv+O371PjHwjCx/0ScgI6Xw2IilEdHNLhKMBjPZSLh3vNp+ok42YaGMh8B/bwDplLmhS+4Dxv/x2ddolqQAO4XDrVwVTeA2BGj17SBxZwzl/OJDjPZyOG37MpaSAhGZg63yPY8xRwNp+fQxgAmVyEiCpeoxJPdxg9JnxqnRw58/AaQq/9xgbHMcY2dY9Gp+0TGcw1ITXUnZPJiv2PsPRoxGJi70L5df/yl9acMoxZG2x89E1JMBVSUdxvSeCHInTEVcMFwfDmDUrWabAAmt6N1qPjO3NXUcWWW3fnAF9ajnfMG6EIo39ij+TJEM5k1Ud+UUYI/n7tCL35GhC34J6TsnPnxnt24GzdqMyBIp6NgmcCvaOZoPbRd+J8MjGRsWbE2m2oiQSQn3F+cVnHCRbb5UzcoRIt1xGN3wZASmz0Hs+cgAIWmREW7ApRGMfM7pUI+7aCidbt7MWEtfYfJK9GVz+FU0=",
      "username": "AgBnCi0Bh1iDaAYvKUlA2gRfkTqeD6cvA8UAkVeumH0PaBGTG0OqWI3DyqDq2Jq19PpOQIuMMXmNdo2wKWhClja7TheBI18hknbCZZcdrQp8n2p8Kx7FIdrkWz2lWYrgtrvrFV3L7A6LEDJEBNCV0JToGrp2n5P0nmUeTB5OWMewesLj0AGs2bZN4DOZE1z/kVChd8MygKiy8v4P/OqakTNs49mhsOYeeKcAw7g+zjK5sPg1SkN1nv7oCFighRvxi7738bMHKd/blpmoasGKXABX3/U7kIR8GTE0mqZ9nUP0ldzniS0B1kMEmlL4ZjcN1N1O9eaj+dZIJVxtExZPliki/IHVLrup8iUzcsYotOQ+8afs6jrbybYzaCwKQifF9FLKANtsoLhlC3KCRU+Yk3OPNHtBxosfh+pAppcpRIybzgVoatdIPi+RhGQ7bZApM5mu9DUpB5fG1d9FGbDjF5jt2kahoP0sYOX39M8XcO4DdZlw4x8aNpAbNuPLj7xhJukp8cqScM21fW3Y1to8fBIaR/j+V9YhO9WDANk/2KWf/l8tcUJq0wy2YXW96g6HxiWzq1NflNeRpO9M7+PPTn7UCR5+0ryfO9YkaQij/T8zkUgVJfPPNcy39Hos+gA1FccFVXJMLes8abIq4hfgP5n8toLNkwMRbUTi17BKggvFDbqP/g61OnVdwMCcDtCEfyYgMveMo0h0fEVjsA=="
    }
  }
}
