{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "paypal-cert",
    "namespace": "training",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "paypal-cert",
        "namespace": "training",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "paypal.crt": "AgBpYZHfUTkp9NJCAXoZbOu235MZFeFY2a4bbYdJ5JW6qor24rkukRqQ7rKhda4Kiik2skbT+9kdPK64hDrxcQqF7jXz281UMIPyArVkXDonQWJ82eFJsdeWmbGxaBhDSFU+33cyzcuoXpaI1nRdgvhNCciJ5t9ZWxzXnrLHlXJvjg66oj/JjArvkNG8/Ydpl2WNr2nXQ5VXh9AIONNEHBXjvtL0iqr3oo5gXgSG1WL/wvnHsduBPECwOrM4XuPgDt38SuWJN9T6GfnpftO5g5MSlqU1jbB8RilwcJSX3B0rn0gEi6KP0e4GtifBLqtgj3QsiOsALVQlczUAo69OQSKitxa1+wLKX4s/PH415eE4RMiCZw3DLlu4GtNvAOVKf/sqsiHaVODBQLtj5AJg3mxbwVRewqrTBYuJYQvoHUkRaXEgVyWvPQaCa4248LBR4Bo5gwJQXkv1KWSXV57vo/On9W48hCv+VsGdZaNn7jb5SGbbHdTlCYlAa9E4bgqqL6AlGWJgZ6DG+OMumIxQm+fyrxTjmke+v0By5qhpSHLdxFiJlHXEWNTrod0SMELw9xZYWGdusoI+M7A9rf3xdb7+m3Mb5zXeYaXsK+pF3F5Z2R7gnBf0SBTdZCYqpirDRagaKn7Alkx88xcunR8yCn/D9Rfaz9Co+j9QwWrN/vAw12C4yuacsIRTB6sklwjw/KifelhL7wCiaGcCoCtLmy0gQ3mX6qb5Hv40cTddKmDk+ZH9ripsHNVzb//AMGPqCdqlrxDZLy2Sl6alC635+Y0DEokPs5vqHHBezY3P3f7Pe7s2RGN2klW988ymC2rpaLrRLxGKS3J4iYHWBTgDQOiuA+Qnj0ZEdTBFhN05UdlQdcM0kdSJ5CqVGWn/lJRuqCCNGyQpo/aWdnVliD3IGPq973k8srL9rUucxePMt05gJiisxQGSJcNHReFa4lTq4jfHKogu3/jumJOd9AVB2Lj/RatQAjk7mrsNnx5UyxXjKPdJmrJC8ykO5pkBBLknDsmOWCPHQyUhYV74dkKgyvzCie4ENc009V21HAyDIvABUhLT11ti2AuD1GmSGpZsS2Xppx+J83NgYV2P7u44YXbmXbDpW62XjPj929KQv7C0RvFiH1Hdc4agVoz9auF2lQdE9jeTZRVRPOzsqnlshHhhhwW3o9U49EVyRraYByCjncyLIc3KkZ5X6bdTnyQIZa5OL0iUcNyqc562+o7+SOQdRS5aLpk9w7wKLOM1FDhOGrGLOdpEdCsYCHAdPBhidT1AJyuVZvgz7k/UnOY5iiFQDBl4v+tLw82VF1YNvPa1bBVlaltwmBKcU/NbG+PZn8LUC1hjy7Rghu5SMowfv+CnDVwgR19I0eMe1+ik73ohvlsK1xIZ3uHipPHoNofLhfw2bE3LLz0rOqLUGorVEZRefXxRgWd36CVUHSqyDltkxxjTPqAKMXzs83XYJlv1o+ugVD7JO3DSbhxmsaXNMoDS/GDrexGn1wrq8Ys7WOEW0Pas7KGADtcnK4SawSXI3kWGQmDzAK7BDNs0pBIt/7XFAyc3uOBZXCJ7AnMR2PhNrLQT2H2rEasIMDRohMRF07Nl6g4GrbK4S01+WAm3n0uY6eRyih36LlbP31T4f5yxfkgio23n6UBVkgD/6O1X+RvfZueMHzxupMiNYBwocXjuCJbdHnlFZgi7S88D9pGB5rSxegiBlvZRkSi8tfsbZtqr/TBBQ/XphhZ85e4WW+nMgk/7Znegzb0BPlFfKBK/15o0CnHf5bPCeyyRCgYl1AOs7M7T9BRNoghWpFSuhrwpX4LZS1HaA4M1ZiK9QXujNmC8HFKdH0jlaelMaGh4m2IMZ85ZfriC3i/sEd0FlTsyod4UIvQf6rzHIbXgiHK1GO1SgL5WDhejqSYVpmS/RC7ebwwT2p2nZlfBEfxogsfduVyI9qJ5wRxCtPEOse4gO99ZCTzgnuCleTW5W2JCTPD73AXsKc+O2jD47oyASYg/H5VpcqplFzZ5g6B2ovHGdh/mXpAR4W77dbGk08o1nRlMPhV4xNKTIaHK1t2uVafHjgOBjRF1BvxP5ghpUY8bK+4A"
    }
  }
}
